spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  batch:
    job:
      enabled: false
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
    root: INFO
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dial  ect
#spring.batch.job.enabled: false
